%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info
options_ = [];
M_.fname = 'TallerNK';
M_.dynare_version = '6.3';
oo_.dynare_version = '6.3';
options_.dynare_version = '6.3';
%
% Some global variables initialization
%
global_initialization;
options_.nograph = true;
M_.exo_names = cell(2,1);
M_.exo_names_tex = cell(2,1);
M_.exo_names_long = cell(2,1);
M_.exo_names(1) = {'eps_a'};
M_.exo_names_tex(1) = {'\varepsilon^{a}'};
M_.exo_names_long(1) = {'TFP Innovations'};
M_.exo_names(2) = {'eps_nu'};
M_.exo_names_tex(2) = {'\varepsilon^{\nu}'};
M_.exo_names_long(2) = {'MP Innovations'};
M_.endo_names = cell(14,1);
M_.endo_names_tex = cell(14,1);
M_.endo_names_long = cell(14,1);
M_.endo_names(1) = {'y_hat'};
M_.endo_names_tex(1) = {'\tilde{y}'};
M_.endo_names_long(1) = {'Output Gap'};
M_.endo_names(2) = {'y'};
M_.endo_names_tex(2) = {'y'};
M_.endo_names_long(2) = {'Real Output'};
M_.endo_names(3) = {'y_n'};
M_.endo_names_tex(3) = {'y^{n}'};
M_.endo_names_long(3) = {'Natural Output'};
M_.endo_names(4) = {'pi'};
M_.endo_names_tex(4) = {'\pi'};
M_.endo_names_long(4) = {'Inflation Rate'};
M_.endo_names(5) = {'n'};
M_.endo_names_tex(5) = {'n'};
M_.endo_names_long(5) = {'Working Hours'};
M_.endo_names(6) = {'i'};
M_.endo_names_tex(6) = {'i'};
M_.endo_names_long(6) = {'Nominal Interest Rate'};
M_.endo_names(7) = {'r'};
M_.endo_names_tex(7) = {'r'};
M_.endo_names_long(7) = {'Real Interest Rate'};
M_.endo_names(8) = {'r_n'};
M_.endo_names_tex(8) = {'r^{n}'};
M_.endo_names_long(8) = {'Real Natural Interest Rate'};
M_.endo_names(9) = {'a'};
M_.endo_names_tex(9) = {'a'};
M_.endo_names_long(9) = {'Total Factor Productivity'};
M_.endo_names(10) = {'nu'};
M_.endo_names_tex(10) = {'\nu'};
M_.endo_names_long(10) = {'Monetary Policy Shock'};
M_.endo_names(11) = {'i_ann'};
M_.endo_names_tex(11) = {'i^{A}'};
M_.endo_names_long(11) = {'Annual Nom Int Rate'};
M_.endo_names(12) = {'pi_ann'};
M_.endo_names_tex(12) = {'\pi^{A}'};
M_.endo_names_long(12) = {'Annual Inflation'};
M_.endo_names(13) = {'r_ann'};
M_.endo_names_tex(13) = {'r^{A}'};
M_.endo_names_long(13) = {'Annual Real Rate'};
M_.endo_names(14) = {'r_n_ann'};
M_.endo_names_tex(14) = {'{r^{n}}^{A}'};
M_.endo_names_long(14) = {'Annual Natural Rate'};
M_.endo_partitions = struct();
M_.param_names = cell(15,1);
M_.param_names_tex = cell(15,1);
M_.param_names_long = cell(15,1);
M_.param_names(1) = {'beta'};
M_.param_names_tex(1) = {'beta'};
M_.param_names_long(1) = {'beta'};
M_.param_names(2) = {'sigma'};
M_.param_names_tex(2) = {'sigma'};
M_.param_names_long(2) = {'sigma'};
M_.param_names(3) = {'varphi'};
M_.param_names_tex(3) = {'varphi'};
M_.param_names_long(3) = {'varphi'};
M_.param_names(4) = {'alpha'};
M_.param_names_tex(4) = {'alpha'};
M_.param_names_long(4) = {'alpha'};
M_.param_names(5) = {'epsilon'};
M_.param_names_tex(5) = {'epsilon'};
M_.param_names_long(5) = {'epsilon'};
M_.param_names(6) = {'theta'};
M_.param_names_tex(6) = {'theta'};
M_.param_names_long(6) = {'theta'};
M_.param_names(7) = {'eta'};
M_.param_names_tex(7) = {'eta'};
M_.param_names_long(7) = {'eta'};
M_.param_names(8) = {'phi_pi'};
M_.param_names_tex(8) = {'phi\_pi'};
M_.param_names_long(8) = {'phi_pi'};
M_.param_names(9) = {'phi_y'};
M_.param_names_tex(9) = {'phi\_y'};
M_.param_names_long(9) = {'phi_y'};
M_.param_names(10) = {'rho_nu'};
M_.param_names_tex(10) = {'rho\_nu'};
M_.param_names_long(10) = {'rho_nu'};
M_.param_names(11) = {'rho_a'};
M_.param_names_tex(11) = {'rho\_a'};
M_.param_names_long(11) = {'rho_a'};
M_.param_names(12) = {'rho'};
M_.param_names_tex(12) = {'rho'};
M_.param_names_long(12) = {'rho'};
M_.param_names(13) = {'mu'};
M_.param_names_tex(13) = {'mu'};
M_.param_names_long(13) = {'mu'};
M_.param_names(14) = {'rho_i'};
M_.param_names_tex(14) = {'rho\_i'};
M_.param_names_long(14) = {'rho_i'};
M_.param_names(15) = {'h'};
M_.param_names_tex(15) = {'h'};
M_.param_names_long(15) = {'h'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 2;
M_.endo_nbr = 14;
M_.param_nbr = 15;
M_.orig_endo_nbr = 14;
M_.aux_vars = [];
M_.Sigma_e = zeros(2, 2);
M_.Correlation_matrix = eye(2, 2);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.learnt_shocks = [];
M_.learnt_endval = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
M_.matched_irfs = {};
M_.matched_irfs_weights = {};
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.ramsey_policy = false;
options_.discretionary_policy = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.eq_nbr = 14;
M_.ramsey_orig_eq_nbr = 0;
M_.ramsey_orig_endo_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 1 6 20;
 0 7 0;
 0 8 0;
 2 9 21;
 0 10 0;
 3 11 0;
 0 12 0;
 0 13 0;
 4 14 0;
 5 15 0;
 0 16 0;
 0 17 0;
 0 18 0;
 0 19 0;]';
M_.nstatic = 9;
M_.nfwrd   = 0;
M_.npred   = 3;
M_.nboth   = 2;
M_.nsfwrd   = 2;
M_.nspred   = 5;
M_.ndynamic   = 5;
M_.dynamic_tmp_nbr = [2; 0; 0; 0; ];
M_.equations_tags = {
  1 , 'name' , 'pi' ;
  2 , 'name' , 'y_hat' ;
  3 , 'name' , 'r_n' ;
  4 , 'name' , 'i' ;
  5 , 'name' , 'nu' ;
  6 , 'name' , 'a' ;
  7 , 'name' , '7' ;
  8 , 'name' , 'y_n' ;
  9 , 'name' , 'y' ;
  10 , 'name' , 'r' ;
  11 , 'name' , 'i_ann' ;
  12 , 'name' , 'r_ann' ;
  13 , 'name' , 'r_n_ann' ;
  14 , 'name' , 'pi_ann' ;
};
M_.mapping.y_hat.eqidx = [1 2 4 7 ];
M_.mapping.y.eqidx = [7 9 ];
M_.mapping.y_n.eqidx = [7 8 ];
M_.mapping.pi.eqidx = [1 2 4 10 14 ];
M_.mapping.n.eqidx = [9 ];
M_.mapping.i.eqidx = [2 4 10 11 ];
M_.mapping.r.eqidx = [10 12 ];
M_.mapping.r_n.eqidx = [2 3 13 ];
M_.mapping.a.eqidx = [3 6 8 9 ];
M_.mapping.nu.eqidx = [4 5 ];
M_.mapping.i_ann.eqidx = [11 ];
M_.mapping.pi_ann.eqidx = [14 ];
M_.mapping.r_ann.eqidx = [12 ];
M_.mapping.r_n_ann.eqidx = [13 ];
M_.mapping.eps_a.eqidx = [6 ];
M_.mapping.eps_nu.eqidx = [5 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.block_structure.time_recursive = false;
M_.block_structure.block(1).Simulation_Type = 1;
M_.block_structure.block(1).endo_nbr = 5;
M_.block_structure.block(1).mfs = 5;
M_.block_structure.block(1).equation = [ 5 6 8 3 13];
M_.block_structure.block(1).variable = [ 10 9 3 8 14];
M_.block_structure.block(1).is_linear = true;
M_.block_structure.block(1).NNZDerivatives = 11;
M_.block_structure.block(1).bytecode_jacob_cols_to_sparse = [1 2 6 7 8 9 10 ];
M_.block_structure.block(2).Simulation_Type = 8;
M_.block_structure.block(2).endo_nbr = 3;
M_.block_structure.block(2).mfs = 3;
M_.block_structure.block(2).equation = [ 4 2 1];
M_.block_structure.block(2).variable = [ 6 1 4];
M_.block_structure.block(2).is_linear = true;
M_.block_structure.block(2).NNZDerivatives = 13;
M_.block_structure.block(2).bytecode_jacob_cols_to_sparse = [1 2 3 4 5 6 8 9 ];
M_.block_structure.block(3).Simulation_Type = 1;
M_.block_structure.block(3).endo_nbr = 2;
M_.block_structure.block(3).mfs = 2;
M_.block_structure.block(3).equation = [ 10 14];
M_.block_structure.block(3).variable = [ 7 12];
M_.block_structure.block(3).is_linear = true;
M_.block_structure.block(3).NNZDerivatives = 2;
M_.block_structure.block(3).bytecode_jacob_cols_to_sparse = [3 4 ];
M_.block_structure.block(4).Simulation_Type = 3;
M_.block_structure.block(4).endo_nbr = 1;
M_.block_structure.block(4).mfs = 1;
M_.block_structure.block(4).equation = [ 7];
M_.block_structure.block(4).variable = [ 2];
M_.block_structure.block(4).is_linear = true;
M_.block_structure.block(4).NNZDerivatives = 1;
M_.block_structure.block(4).bytecode_jacob_cols_to_sparse = [1 ];
M_.block_structure.block(5).Simulation_Type = 1;
M_.block_structure.block(5).endo_nbr = 2;
M_.block_structure.block(5).mfs = 2;
M_.block_structure.block(5).equation = [ 12 11];
M_.block_structure.block(5).variable = [ 13 11];
M_.block_structure.block(5).is_linear = true;
M_.block_structure.block(5).NNZDerivatives = 2;
M_.block_structure.block(5).bytecode_jacob_cols_to_sparse = [3 4 ];
M_.block_structure.block(6).Simulation_Type = 3;
M_.block_structure.block(6).endo_nbr = 1;
M_.block_structure.block(6).mfs = 1;
M_.block_structure.block(6).equation = [ 9];
M_.block_structure.block(6).variable = [ 5];
M_.block_structure.block(6).is_linear = true;
M_.block_structure.block(6).NNZDerivatives = 1;
M_.block_structure.block(6).bytecode_jacob_cols_to_sparse = [1 ];
M_.block_structure.block(1).g1_sparse_rowval = int32([]);
M_.block_structure.block(1).g1_sparse_colval = int32([]);
M_.block_structure.block(1).g1_sparse_colptr = int32([]);
M_.block_structure.block(2).g1_sparse_rowval = int32([1 2 3 1 2 1 2 3 1 3 2 2 3 ]);
M_.block_structure.block(2).g1_sparse_colval = int32([1 2 3 4 4 5 5 5 6 6 8 9 9 ]);
M_.block_structure.block(2).g1_sparse_colptr = int32([1 2 3 4 6 9 11 11 12 14 ]);
M_.block_structure.block(3).g1_sparse_rowval = int32([]);
M_.block_structure.block(3).g1_sparse_colval = int32([]);
M_.block_structure.block(3).g1_sparse_colptr = int32([]);
M_.block_structure.block(4).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(4).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(4).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(5).g1_sparse_rowval = int32([]);
M_.block_structure.block(5).g1_sparse_colval = int32([]);
M_.block_structure.block(5).g1_sparse_colptr = int32([]);
M_.block_structure.block(6).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(6).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(6).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.variable_reordered = [ 10 9 3 8 14 6 1 4 7 12 2 13 11 5];
M_.block_structure.equation_reordered = [ 5 6 8 3 13 4 2 1 10 14 7 12 11 9];
M_.block_structure.incidence(1).lead_lag = -1;
M_.block_structure.incidence(1).sparse_IM = [
 1 4;
 2 1;
 3 9;
 4 6;
 5 10;
 6 9;
 8 9;
 9 9;
];
M_.block_structure.incidence(2).lead_lag = 0;
M_.block_structure.incidence(2).sparse_IM = [
 1 1;
 1 4;
 2 1;
 2 6;
 2 8;
 3 8;
 3 9;
 4 1;
 4 4;
 4 6;
 4 10;
 5 10;
 6 9;
 7 1;
 7 2;
 7 3;
 8 3;
 9 2;
 9 5;
 10 6;
 10 7;
 11 6;
 11 11;
 12 7;
 12 13;
 13 8;
 13 14;
 14 4;
 14 12;
];
M_.block_structure.incidence(3).lead_lag = 1;
M_.block_structure.incidence(3).sparse_IM = [
 1 4;
 2 1;
 2 4;
 10 4;
];
M_.block_structure.dyn_tmp_nbr = 1;
M_.state_var = [10 9 6 1 4 ];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(14, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(2, 1);
M_.params = NaN(15, 1);
M_.endo_trends = struct('deflator', cell(14, 1), 'log_deflator', cell(14, 1), 'growth_factor', cell(14, 1), 'log_growth_factor', cell(14, 1));
M_.NNZDerivatives = [43; 0; -1; ];
M_.dynamic_g1_sparse_rowval = int32([2 1 4 3 6 8 9 5 1 2 4 7 7 9 7 8 1 4 14 9 2 4 10 11 10 12 2 3 13 3 6 4 5 11 14 12 13 2 1 2 10 6 5 ]);
M_.dynamic_g1_sparse_colval = int32([1 4 6 9 9 9 9 10 15 15 15 15 16 16 17 17 18 18 18 19 20 20 20 20 21 21 22 22 22 23 23 24 24 25 26 27 28 29 32 32 32 43 44 ]);
M_.dynamic_g1_sparse_colptr = int32([1 2 2 2 3 3 4 4 4 8 9 9 9 9 9 13 15 17 20 21 25 27 30 32 34 35 36 37 38 39 39 39 42 42 42 42 42 42 42 42 42 42 42 43 44 ]);
M_.dynamic_g2_sparse_indices = int32([]);
M_.lhs = {
'pi'; 
'y_hat'; 
'r_n'; 
'i'; 
'nu'; 
'a'; 
'y_hat'; 
'y_n'; 
'y'; 
'r'; 
'i_ann'; 
'r_ann'; 
'r_n_ann'; 
'pi_ann'; 
};
M_.static_tmp_nbr = [2; 0; 0; 0; ];
M_.block_structure_stat.block(1).Simulation_Type = 1;
M_.block_structure_stat.block(1).endo_nbr = 1;
M_.block_structure_stat.block(1).mfs = 1;
M_.block_structure_stat.block(1).equation = [ 3];
M_.block_structure_stat.block(1).variable = [ 8];
M_.block_structure_stat.block(2).Simulation_Type = 3;
M_.block_structure_stat.block(2).endo_nbr = 1;
M_.block_structure_stat.block(2).mfs = 1;
M_.block_structure_stat.block(2).equation = [ 5];
M_.block_structure_stat.block(2).variable = [ 10];
M_.block_structure_stat.block(3).Simulation_Type = 3;
M_.block_structure_stat.block(3).endo_nbr = 1;
M_.block_structure_stat.block(3).mfs = 1;
M_.block_structure_stat.block(3).equation = [ 6];
M_.block_structure_stat.block(3).variable = [ 9];
M_.block_structure_stat.block(4).Simulation_Type = 1;
M_.block_structure_stat.block(4).endo_nbr = 2;
M_.block_structure_stat.block(4).mfs = 2;
M_.block_structure_stat.block(4).equation = [ 8 13];
M_.block_structure_stat.block(4).variable = [ 3 14];
M_.block_structure_stat.block(5).Simulation_Type = 6;
M_.block_structure_stat.block(5).endo_nbr = 3;
M_.block_structure_stat.block(5).mfs = 3;
M_.block_structure_stat.block(5).equation = [ 1 2 4];
M_.block_structure_stat.block(5).variable = [ 1 4 6];
M_.block_structure_stat.block(6).Simulation_Type = 1;
M_.block_structure_stat.block(6).endo_nbr = 2;
M_.block_structure_stat.block(6).mfs = 2;
M_.block_structure_stat.block(6).equation = [ 10 14];
M_.block_structure_stat.block(6).variable = [ 7 12];
M_.block_structure_stat.block(7).Simulation_Type = 3;
M_.block_structure_stat.block(7).endo_nbr = 1;
M_.block_structure_stat.block(7).mfs = 1;
M_.block_structure_stat.block(7).equation = [ 7];
M_.block_structure_stat.block(7).variable = [ 2];
M_.block_structure_stat.block(8).Simulation_Type = 1;
M_.block_structure_stat.block(8).endo_nbr = 2;
M_.block_structure_stat.block(8).mfs = 2;
M_.block_structure_stat.block(8).equation = [ 12 11];
M_.block_structure_stat.block(8).variable = [ 13 11];
M_.block_structure_stat.block(9).Simulation_Type = 3;
M_.block_structure_stat.block(9).endo_nbr = 1;
M_.block_structure_stat.block(9).mfs = 1;
M_.block_structure_stat.block(9).equation = [ 9];
M_.block_structure_stat.block(9).variable = [ 5];
M_.block_structure_stat.variable_reordered = [ 8 10 9 3 14 1 4 6 7 12 2 13 11 5];
M_.block_structure_stat.equation_reordered = [ 3 5 6 8 13 1 2 4 10 14 7 12 11 9];
M_.block_structure_stat.incidence.sparse_IM = [
 1 1;
 1 4;
 2 1;
 2 4;
 2 6;
 2 8;
 3 8;
 4 1;
 4 4;
 4 6;
 4 10;
 5 10;
 6 9;
 7 1;
 7 2;
 7 3;
 8 3;
 8 9;
 9 2;
 9 5;
 9 9;
 10 4;
 10 6;
 10 7;
 11 6;
 11 11;
 12 7;
 12 13;
 13 8;
 13 14;
 14 4;
 14 12;
];
M_.block_structure_stat.tmp_nbr = 1;
M_.block_structure_stat.block(1).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(1).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(1).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(2).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(3).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(3).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(3).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(4).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(4).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(4).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(5).g1_sparse_rowval = int32([1 2 3 1 2 3 2 3 ]);
M_.block_structure_stat.block(5).g1_sparse_colval = int32([1 1 1 2 2 2 3 3 ]);
M_.block_structure_stat.block(5).g1_sparse_colptr = int32([1 4 7 9 ]);
M_.block_structure_stat.block(6).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(6).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(6).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(7).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(7).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(7).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(8).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(8).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(8).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(9).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(9).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(9).g1_sparse_colptr = int32([1 2 ]);
M_.static_g1_sparse_rowval = int32([1 2 4 7 7 9 7 8 1 2 4 10 14 9 2 4 10 11 10 12 2 3 13 6 8 9 4 5 11 14 12 13 ]);
M_.static_g1_sparse_colval = int32([1 1 1 1 2 2 3 3 4 4 4 4 4 5 6 6 6 6 7 7 8 8 8 9 9 9 10 10 11 12 13 14 ]);
M_.static_g1_sparse_colptr = int32([1 5 7 9 14 15 19 21 24 27 29 30 31 32 33 ]);
close all;
M_.params(1) = 0.99;
beta = M_.params(1);
M_.params(2) = 1;
sigma = M_.params(2);
M_.params(3) = 1;
varphi = M_.params(3);
M_.params(4) = 0.3333333333333333;
alpha = M_.params(4);
M_.params(5) = 6;
epsilon = M_.params(5);
M_.params(6) = 0.6666666666666666;
theta = M_.params(6);
M_.params(8) = 1.5;
phi_pi = M_.params(8);
M_.params(7) = 4;
eta = M_.params(7);
M_.params(9) = 0.125;
phi_y = M_.params(9);
M_.params(10) = 0.5;
rho_nu = M_.params(10);
M_.params(11) = 0.9;
rho_a = M_.params(11);
M_.params(13) = log(M_.params(5)/(M_.params(5)-1));
mu = M_.params(13);
M_.params(12) = (-log(M_.params(1)));
rho = M_.params(12);
M_.params(14) = 0.5;
rho_i = M_.params(14);
M_.params(15) = 0.8;
h = M_.params(15);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 0.0625;
M_.Sigma_e(2, 2) = 0.0625;
options_resid_ = struct();
display_static_residuals(M_, options_, oo_, options_resid_);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 20;
options_.order = 1;
options_.relative_irf = true;
var_list_ = {};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'TallerNK_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'TallerNK_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'TallerNK_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'TallerNK_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'TallerNK_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'TallerNK_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'TallerNK_results.mat'], 'oo_recursive_', '-append');
end
if exist('options_mom_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'TallerNK_results.mat'], 'options_mom_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
